"""users phone unique

Revision ID: 042505663170
Revises: a4d87c16fe19
Create Date: 2023-03-18 18:11:25.396531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "042505663170"
down_revision = "a4d87c16fe19"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_phone", table_name="users")
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.create_index("ix_users_phone", "users", ["phone"], unique=False)
    # ### end Alembic commands ###
