"""users sessions devices

Revision ID: 45032991e05e
Revises: d2960e87478c
Create Date: 2023-03-18 20:11:25.396531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "45032991e05e"
down_revision = "d2960e87478c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions_devices",
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("device_type", sa.String(), nullable=True),
        sa.Column("device_brand", sa.String(), nullable=True),
        sa.Column("device_family", sa.String(), nullable=True),
        sa.Column("os_family", sa.String(), nullable=True),
        sa.Column("os_version", sa.String(), nullable=True),
        sa.Column("browser_family", sa.String(), nullable=True),
        sa.Column("browser_version", sa.String(), nullable=True),
        sa.Column("ip", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.add_column(
        "users_sessions",
        sa.Column("device_id", postgresql.UUID(as_uuid=True), nullable=False),
    )
    op.add_column(
        "users_sessions", sa.Column("status_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "users_sessions", "statuses", ["status_id"], ["id"]
    )
    op.create_foreign_key(
        None, "users_sessions", "sessions_devices", ["device_id"], ["uuid"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users_sessions", type_="foreignkey")
    op.drop_constraint(None, "users_sessions", type_="foreignkey")
    op.drop_column("users_sessions", "status_id")
    op.drop_column("users_sessions", "device_id")
    op.drop_table("sessions_devices")
    # ### end Alembic commands ###
