"""rename author to author_id

Revision ID: 4b5f79b1a4bf
Revises: e784c6db707a
Create Date: 2022-10-25 14:31:10.913654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4b5f79b1a4bf"
down_revision = "e784c6db707a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column("author_id", postgresql.UUID(as_uuid=True), nullable=False),
    )
    op.drop_constraint("messages_author_fkey", "messages", type_="foreignkey")
    op.create_foreign_key(None, "messages", "users", ["author_id"], ["uuid"])
    op.drop_column("messages", "author")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "author", postgresql.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.create_foreign_key(
        "messages_author_fkey", "messages", "users", ["author"], ["uuid"]
    )
    op.drop_column("messages", "author_id")
    # ### end Alembic commands ###
