"""fix photos

Revision ID: 798f93615ed2
Revises: eca27fd94f5c
Create Date: 2023-03-19 00:12:02.905448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '798f93615ed2'
down_revision = 'eca27fd94f5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'documents',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('document_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('filename', sa.Text(), nullable=True),
        sa.Column('size_bytes', sa.Numeric(), nullable=True),
        sa.Column('mime_type', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('uuid')
        )
    op.create_foreign_key(None, 'chats', 'documents', ['document_id'], ['uuid'])
    op.create_foreign_key(None, 'messages_documents', 'documents', ['document_id'], ['uuid'])
    op.drop_column('users', 'avatar_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('avatar_id', postgresql.UUID(), autoincrement=False, nullable=True)
        )
    op.drop_constraint(None, 'messages_documents', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_table('documents')
    # ### end Alembic commands ###
