"""parent to messages

Revision ID: 8b5e344dda78
Revises: 4b5f79b1a4bf
Create Date: 2022-10-26 21:26:12.041197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8b5e344dda78"
down_revision = "4b5f79b1a4bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    RAW_PRIMARY = """
    alter table messages
    add primary key (uuid);
    """
    op.execute(RAW_PRIMARY)
    op.add_column(
        "messages",
        sa.Column("parent_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        None,
        "messages",
        "messages",
        ["parent_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_column("messages", "parent_id")
    # ### end Alembic commands ###
