"""fix photos avatar

Revision ID: 9b5861d48621
Revises: ce89a0b2e4b5
Create Date: 2023-03-19 00:23:04.440932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b5861d48621'
down_revision = 'ce89a0b2e4b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'users', 'documents', ['avatar_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_id')
    # ### end Alembic commands ###
