"""messages_documents update

Revision ID: 9d0be1c3bebd
Revises: 5509f4d52840
Create Date: 2023-03-18 16:38:09.992062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d0be1c3bebd'
down_revision = '5509f4d52840'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_document_id_fkey', 'chats', type_='foreignkey')
    op.drop_constraint(
        'messages_documents_document_id_fkey', 'messages_documents', type_='foreignkey'
    )
    op.drop_table('documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        'messages_documents_document_id_fkey', 'messages_documents', 'documents', ['document_id'],
        ['uuid']
        )
    op.create_foreign_key('chats_document_id_fkey', 'chats', 'documents', ['document_id'], ['uuid'])
    op.create_table(
        'documents',
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('security_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('size_bytes', sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column('mime_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name='documents_status_id_fkey'),
        sa.PrimaryKeyConstraint('uuid', name='documents_pkey')
        )
    # ### end Alembic commands ###
