"""add avatar to user

Revision ID: a899bee1ad92
Revises: 9d0be1c3bebd
Create Date: 2023-03-18 17:18:48.261266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a899bee1ad92'
down_revision = '9d0be1c3bebd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
