"""fix photos

Revision ID: ce89a0b2e4b5
Revises: 798f93615ed2
Create Date: 2023-03-19 00:21:21.008477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce89a0b2e4b5'
down_revision = '798f93615ed2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
