"""added session type

Revision ID: d4cc52808a5d
Revises: 45032991e05e
Create Date: 2023-03-19 09:13:31.554343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d4cc52808a5d"
down_revision = "45032991e05e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    enum_sql = "create type SessionTypeEnum as enum ('REGISTER', 'AUTH');"
    op.execute(enum_sql)
    op.add_column(
        "users_sessions",
        sa.Column(
            "session_type",
            sa.Enum("REGISTER", "AUTH", name="sessiontypeenum"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_sessions", "session_type")
    # ### end Alembic commands ###
