"""update users

Revision ID: e201b0068a71
Revises: d1a85a243347
Create Date: 2023-03-19 06:59:32.602238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e201b0068a71"
down_revision = "d1a85a243347"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("login", sa.String(), nullable=False))
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("last_name", sa.String(length=255), nullable=True)
    )
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "login")
    # ### end Alembic commands ###
