"""remove recipient

Revision ID: e784c6db707a
Revises: ffd97edf99ba
Create Date: 2023-03-19 11:17:25.396531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e784c6db707a"
down_revision = "ffd97edf99ba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "conversations_recipient_id_fkey", "conversations", type_="foreignkey"
    )
    op.drop_column("conversations", "recipient_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column(
            "recipient_id",
            postgresql.UUID(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "conversations_recipient_id_fkey",
        "conversations",
        "users",
        ["recipient_id"],
        ["uuid"],
    )
    # ### end Alembic commands ###
