"""add avatar to user2

Revision ID: eca27fd94f5c
Revises: a899bee1ad92
Create Date: 2023-03-18 17:19:51.542613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eca27fd94f5c'
down_revision = 'a899bee1ad92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_id', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_id')
    # ### end Alembic commands ###
