"""add last_activity

Revision ID: f9d09737883a
Revises: 8b5e344dda78
Create Date: 2023-03-15 02:58:42.927745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d09737883a'
down_revision = '8b5e344dda78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_activity', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_activity')
    op.drop_column('users', 'is_online')
    # ### end Alembic commands ###
